const voiceExplorationSamples = {
  "sample_text": "Various texts (see individual samples)",
  "base_path": "/home/tdeshane/movie_maker/hdmy5movie_voices/explore",
  "date_generated": "2025-03-16T01:18:28.066430",
  "samples": [
    {
      "id": 372,
      "filename": "speaker_4_temp_0.75_topk_50_medium_372.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.75,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with moderate expressivity and natural flow and balanced vocabulary diversity using medium style",
      "generation_time": "208.74s",
      "text": "Electronic beeps and ambient synth create tension as the player navigates through a dimly lit abandoned research facility."
    },
    {
      "id": 34,
      "filename": "speaker_0_temp_0.9_topk_20_accent_variation_34.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.9,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Medium-pitched female voice with clear articulation with balanced expressivity and consistency and focused and consistent word choices using accent_variation style",
      "generation_time": "62.76s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 227,
      "filename": "speaker_2_temp_1.1_topk_20_emotional_227.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using emotional style",
      "generation_time": "118.56s",
      "text": "[excited] We've finally discovered the artifact after years of searching!"
    },
    {
      "id": 581,
      "filename": "speaker_6_temp_1.1_topk_20_game_instructions_581.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.1,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with high expressivity and natural variation and focused and consistent word choices using game_instructions style",
      "generation_time": "150.48s",
      "text": "Press X to jump and hold Circle to charge your special attack."
    },
    {
      "id": 422,
      "filename": "speaker_4_temp_1.3_topk_20_medium_422.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "282.51s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 276,
      "filename": "speaker_3_temp_0.5_topk_80_technical_276.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 0.5,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Young female voice with higher pitch with low randomness and consistent delivery and diverse and potentially creative phrasing using technical style",
      "generation_time": "197.55s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 18,
      "filename": "speaker_0_temp_0.75_topk_20_game_instructions_18.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.75,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Medium-pitched female voice with clear articulation with moderate expressivity and natural flow and focused and consistent word choices using game_instructions style",
      "generation_time": "586.32s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 151,
      "filename": "speaker_1_temp_1.1_topk_80_medium_151.wav",
      "exists": true,
      "speaker_id": 1,
      "temperature": 1.1,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Deep female voice with dramatic tone with high expressivity and natural variation and diverse and potentially creative phrasing using medium style",
      "generation_time": "228.07s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 338,
      "filename": "speaker_3_temp_1.3_topk_20_accent_variation_338.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 1.3,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Young female voice with higher pitch with maximum expressivity and creativity and focused and consistent word choices using accent_variation style",
      "generation_time": "98.63s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 677,
      "filename": "speaker_7_temp_1.1_topk_50_accent_variation_677.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using accent_variation style",
      "generation_time": "80.79s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 394,
      "filename": "speaker_4_temp_0.9_topk_80_short_394.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with balanced expressivity and consistency and diverse and potentially creative phrasing using short style",
      "generation_time": "85.23s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 255,
      "filename": "speaker_2_temp_1.3_topk_50_conversation_255.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and balanced vocabulary diversity using conversation style",
      "generation_time": "83.36s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 385,
      "filename": "speaker_4_temp_0.9_topk_20_game_instructions_385.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with balanced expressivity and consistency and focused and consistent word choices using game_instructions style",
      "generation_time": "123.76s",
      "text": "Collect the blue crystals to upgrade your character's abilities in the skill tree."
    },
    {
      "id": 524,
      "filename": "speaker_5_temp_1.3_topk_80_technical_524.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and diverse and potentially creative phrasing using technical style",
      "generation_time": "190.42s",
      "text": "The quantum entanglement device initializes its calibration sequence, emitting a soft blue glow throughout the laboratory."
    },
    {
      "id": 246,
      "filename": "speaker_2_temp_1.3_topk_20_medium_246.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "244.18s",
      "text": "Rhythmic tribal drums accompany the hero's journey through dense jungle foliage, occasionally interrupted by exotic wildlife calls."
    },
    {
      "id": 510,
      "filename": "speaker_5_temp_1.3_topk_20_medium_510.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "191.25s",
      "text": "Electronic beeps and ambient synth create tension as the player navigates through a dimly lit abandoned research facility."
    },
    {
      "id": 298,
      "filename": "speaker_3_temp_0.9_topk_20_accent_variation_298.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 0.9,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Young female voice with higher pitch with balanced expressivity and consistency and focused and consistent word choices using accent_variation style",
      "generation_time": "144.84s",
      "text": "[british] I say, this adventure is turning out to be quite splendid!"
    },
    {
      "id": 448,
      "filename": "speaker_5_temp_0.5_topk_50_conversation_448.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.5,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with low randomness and consistent delivery and balanced vocabulary diversity using conversation style",
      "generation_time": "68.90s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 7,
      "filename": "speaker_0_temp_0.5_topk_50_technical_7.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.5,
      "topk": 50,
      "style": "technical",
      "has_context": false,
      "description": "Medium-pitched female voice with clear articulation with low randomness and consistent delivery and balanced vocabulary diversity using technical style",
      "generation_time": "184.53s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 300,
      "filename": "speaker_3_temp_0.9_topk_50_medium_300.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 0.9,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Young female voice with higher pitch with balanced expressivity and consistency and balanced vocabulary diversity using medium style",
      "generation_time": "254.68s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 167,
      "filename": "speaker_1_temp_1.3_topk_50_conversation_167.wav",
      "exists": true,
      "speaker_id": 1,
      "temperature": 1.3,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Deep female voice with dramatic tone with maximum expressivity and creativity and balanced vocabulary diversity using conversation style",
      "generation_time": "70.31s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 472,
      "filename": "speaker_5_temp_0.9_topk_20_conversation_472.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.9,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with balanced expressivity and consistency and focused and consistent word choices using conversation style",
      "generation_time": "67.53s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 68,
      "filename": "speaker_0_temp_1.1_topk_80_accent_variation_68.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 1.1,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Medium-pitched female voice with clear articulation with high expressivity and natural variation and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "180.74s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 51,
      "filename": "speaker_0_temp_1.1_topk_20_emotional_51.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 1.1,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Medium-pitched female voice with clear articulation with high expressivity and natural variation and focused and consistent word choices using emotional style",
      "generation_time": "137.89s",
      "text": "[suspenseful] The countdown timer flashes red as oxygen levels drop to critical levels."
    },
    {
      "id": 458,
      "filename": "speaker_5_temp_0.75_topk_20_game_instructions_458.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.75,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with moderate expressivity and natural flow and focused and consistent word choices using game_instructions style",
      "generation_time": "224.44s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    },
    {
      "id": 506,
      "filename": "speaker_5_temp_1.1_topk_80_conversation_506.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using conversation style",
      "generation_time": "61.37s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 230,
      "filename": "speaker_2_temp_1.1_topk_20_accent_variation_230.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using accent_variation style",
      "generation_time": "88.53s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 613,
      "filename": "speaker_6_temp_1.3_topk_80_emotional_613.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.3,
      "topk": 80,
      "style": "emotional",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with maximum expressivity and creativity and diverse and potentially creative phrasing using emotional style",
      "generation_time": "112.64s",
      "text": "[melancholic] The melody echoes memories of a world long forgotten."
    },
    {
      "id": 675,
      "filename": "speaker_7_temp_1.1_topk_50_conversation_675.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using conversation style",
      "generation_time": "81.61s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 23,
      "filename": "speaker_0_temp_0.75_topk_50_game_instructions_23.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.75,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Medium-pitched female voice with clear articulation with moderate expressivity and natural flow and balanced vocabulary diversity using game_instructions style",
      "generation_time": "208.00s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    },
    {
      "id": 170,
      "filename": "speaker_1_temp_1.3_topk_80_short_170.wav",
      "exists": true,
      "speaker_id": 1,
      "temperature": 1.3,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Deep female voice with dramatic tone with maximum expressivity and creativity and diverse and potentially creative phrasing using short style",
      "generation_time": "92.38s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 676,
      "filename": "speaker_7_temp_1.1_topk_50_game_instructions_676.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using game_instructions style",
      "generation_time": "115.45s",
      "text": "Press X to jump and hold Circle to charge your special attack."
    },
    {
      "id": 645,
      "filename": "speaker_7_temp_0.9_topk_20_short_645.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 0.9,
      "topk": 20,
      "style": "short",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with balanced expressivity and consistency and focused and consistent word choices using short style",
      "generation_time": "95.34s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 224,
      "filename": "speaker_2_temp_0.9_topk_80_accent_variation_224.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 0.9,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with balanced expressivity and consistency and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "107.80s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 10,
      "filename": "speaker_0_temp_0.5_topk_80_short_10.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.5,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Medium-pitched female voice with clear articulation with low randomness and consistent delivery and diverse and potentially creative phrasing using short style",
      "generation_time": "99.67s",
      "text": "Ancient ruins glow with mysterious blue energy."
    },
    {
      "id": 516,
      "filename": "speaker_5_temp_1.3_topk_50_medium_516.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and balanced vocabulary diversity using medium style",
      "generation_time": "317.86s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 371,
      "filename": "speaker_4_temp_0.75_topk_50_short_371.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.75,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with moderate expressivity and natural flow and balanced vocabulary diversity using short style",
      "generation_time": "87.05s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 406,
      "filename": "speaker_4_temp_1.1_topk_20_accent_variation_406.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.1,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with high expressivity and natural variation and focused and consistent word choices using accent_variation style",
      "generation_time": "119.95s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 456,
      "filename": "speaker_5_temp_0.75_topk_20_medium_456.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.75,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with moderate expressivity and natural flow and focused and consistent word choices using medium style",
      "generation_time": "259.63s",
      "text": "The spacecraft engines roar to life, pushing against the planet's gravity as stars slowly become visible through the clearing atmosphere."
    },
    {
      "id": 104,
      "filename": "speaker_7_temp_1.3_topk_20_conversation_104.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and focused and consistent word choices using conversation style",
      "generation_time": "86.52s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 69,
      "filename": "speaker_5_temp_1.3_topk_50_technical_69.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 50,
      "style": "technical",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and balanced vocabulary diversity using technical style",
      "generation_time": "213.96s",
      "text": "Players can combine lithium deposits with thermal extractors to create advanced power cells for their exosuits."
    },
    {
      "id": 67,
      "filename": "speaker_5_temp_1.3_topk_50_short_67.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and balanced vocabulary diversity using short style",
      "generation_time": "100.79s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 50,
      "filename": "speaker_5_temp_1.1_topk_50_emotional_50.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 50,
      "style": "emotional",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and balanced vocabulary diversity using emotional style",
      "generation_time": "131.65s",
      "text": "[ominous] Something watches from the shadows, tracking your every move."
    },
    {
      "id": 111,
      "filename": "speaker_7_temp_1.3_topk_50_conversation_111.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and balanced vocabulary diversity using conversation style",
      "generation_time": "141.79s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 70,
      "filename": "speaker_5_temp_1.3_topk_50_emotional_70.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 50,
      "style": "emotional",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and balanced vocabulary diversity using emotional style",
      "generation_time": "194.54s",
      "text": "[melancholic] The melody echoes memories of a world long forgotten."
    },
    {
      "id": 42,
      "filename": "speaker_5_temp_1.1_topk_20_medium_42.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and focused and consistent word choices using medium style",
      "generation_time": "340.51s",
      "text": "Electronic beeps and ambient synth create tension as the player navigates through a dimly lit abandoned research facility."
    },
    {
      "id": 26,
      "filename": "speaker_2_temp_1.3_topk_20_accent_variation_26.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and focused and consistent word choices using accent_variation style",
      "generation_time": "176.16s",
      "text": "[british] I say, this adventure is turning out to be quite splendid!"
    },
    {
      "id": 30,
      "filename": "speaker_2_temp_1.3_topk_50_emotional_30.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 50,
      "style": "emotional",
      "has_context": false,
      "description": "Male voice with medium pitch with maximum expressivity and creativity and balanced vocabulary diversity using emotional style",
      "generation_time": "189.23s",
      "text": "[suspenseful] The countdown timer flashes red as oxygen levels drop to critical levels."
    },
    {
      "id": 55,
      "filename": "speaker_5_temp_1.1_topk_80_medium_55.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using medium style",
      "generation_time": "428.61s",
      "text": "Rhythmic tribal drums accompany the hero's journey through dense jungle foliage, occasionally interrupted by exotic wildlife calls."
    },
    {
      "id": 77,
      "filename": "speaker_5_temp_1.3_topk_80_emotional_77.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 80,
      "style": "emotional",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and diverse and potentially creative phrasing using emotional style",
      "generation_time": "258.79s",
      "text": "[suspenseful] The countdown timer flashes red as oxygen levels drop to critical levels."
    },
    {
      "id": 93,
      "filename": "speaker_7_temp_1.1_topk_50_accent_variation_93.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using accent_variation style",
      "generation_time": "149.00s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 71,
      "filename": "speaker_5_temp_1.3_topk_50_conversation_71.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and balanced vocabulary diversity using conversation style",
      "generation_time": "145.94s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 120,
      "filename": "speaker_7_temp_1.3_topk_80_accent_variation_120.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "150.30s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 86,
      "filename": "speaker_7_temp_1.1_topk_20_accent_variation_86.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and focused and consistent word choices using accent_variation style",
      "generation_time": "136.76s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 62,
      "filename": "speaker_5_temp_1.3_topk_20_medium_62.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "452.92s",
      "text": "The spacecraft engines roar to life, pushing against the planet's gravity as stars slowly become visible through the clearing atmosphere."
    },
    {
      "id": 96,
      "filename": "speaker_7_temp_1.1_topk_80_technical_96.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and diverse and potentially creative phrasing using technical style",
      "generation_time": "307.78s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 118,
      "filename": "speaker_7_temp_1.3_topk_80_conversation_118.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and diverse and potentially creative phrasing using conversation style",
      "generation_time": "136.69s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 125,
      "filename": "speaker_7_temp_0.9_topk_50_conversation_with_context_125.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 0.9,
      "topk": 50,
      "style": "conversation",
      "has_context": true,
      "description": "Deep fefemale voice with mature tone with balanced expressivity and consistency and balanced vocabulary diversity using conversation style with conversation context",
      "generation_time": "161.73s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 57,
      "filename": "speaker_5_temp_1.1_topk_80_emotional_57.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "emotional",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using emotional style",
      "generation_time": "223.52s",
      "text": "[melancholic] The melody echoes memories of a world long forgotten."
    },
    {
      "id": 90,
      "filename": "speaker_7_temp_1.1_topk_50_emotional_90.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "emotional",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using emotional style",
      "generation_time": "196.85s",
      "text": "[melancholic] The melody echoes memories of a world long forgotten."
    },
    {
      "id": 11,
      "filename": "speaker_2_temp_1.1_topk_50_conversation_11.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and balanced vocabulary diversity using conversation style",
      "generation_time": "154.99s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 99,
      "filename": "speaker_7_temp_1.1_topk_80_game_instructions_99.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 80,
      "style": "game_instructions",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and diverse and potentially creative phrasing using game_instructions style",
      "generation_time": "398.86s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 103,
      "filename": "speaker_7_temp_1.3_topk_20_emotional_103.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and focused and consistent word choices using emotional style",
      "generation_time": "328.18s",
      "text": "[melancholic] The melody echoes memories of a world long forgotten."
    },
    {
      "id": 100,
      "filename": "speaker_7_temp_1.1_topk_80_accent_variation_100.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "161.24s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 38,
      "filename": "speaker_2_temp_1.3_topk_80_conversation_38.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and diverse and potentially creative phrasing using conversation style",
      "generation_time": "106.17s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 108,
      "filename": "speaker_7_temp_1.3_topk_50_medium_108.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and balanced vocabulary diversity using medium style",
      "generation_time": "439.77s",
      "text": "The spacecraft engines roar to life, pushing against the planet's gravity as stars slowly become visible through the clearing atmosphere."
    },
    {
      "id": 2,
      "filename": "speaker_2_temp_1.1_topk_20_medium_2.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using medium style",
      "generation_time": "346.94s",
      "text": "Rhythmic tribal drums accompany the hero's journey through dense jungle foliage, occasionally interrupted by exotic wildlife calls."
    },
    {
      "id": 1,
      "filename": "speaker_2_temp_1.1_topk_20_short_1.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "short",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using short style",
      "generation_time": "137.97s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 84,
      "filename": "speaker_7_temp_1.1_topk_20_conversation_84.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and focused and consistent word choices using conversation style",
      "generation_time": "99.72s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 22,
      "filename": "speaker_2_temp_1.3_topk_20_medium_22.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "402.96s",
      "text": "Rhythmic tribal drums accompany the hero's journey through dense jungle foliage, occasionally interrupted by exotic wildlife calls."
    },
    {
      "id": 76,
      "filename": "speaker_5_temp_1.3_topk_80_technical_76.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and diverse and potentially creative phrasing using technical style",
      "generation_time": "397.67s",
      "text": "The quantum entanglement device initializes its calibration sequence, emitting a soft blue glow throughout the laboratory."
    },
    {
      "id": 80,
      "filename": "speaker_5_temp_1.3_topk_80_accent_variation_80.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "142.63s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 44,
      "filename": "speaker_5_temp_1.1_topk_20_conversation_44.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and focused and consistent word choices using conversation style",
      "generation_time": "124.03s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 85,
      "filename": "speaker_7_temp_1.1_topk_20_game_instructions_85.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and focused and consistent word choices using game_instructions style",
      "generation_time": "174.65s",
      "text": "Press X to jump and hold Circle to charge your special attack."
    },
    {
      "id": 59,
      "filename": "speaker_5_temp_1.1_topk_80_game_instructions_59.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "game_instructions",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using game_instructions style",
      "generation_time": "198.25s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 97,
      "filename": "speaker_7_temp_1.1_topk_80_emotional_97.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 80,
      "style": "emotional",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and diverse and potentially creative phrasing using emotional style",
      "generation_time": "167.01s",
      "text": "[ominous] Something watches from the shadows, tracking your every move."
    },
    {
      "id": 91,
      "filename": "speaker_7_temp_1.1_topk_50_conversation_91.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using conversation style",
      "generation_time": "143.18s",
      "text": "Let me think about it. I'll get back to you tomorrow."
    },
    {
      "id": 16,
      "filename": "speaker_2_temp_1.1_topk_80_technical_16.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and diverse and potentially creative phrasing using technical style",
      "generation_time": "355.48s",
      "text": "Players can combine lithium deposits with thermal extractors to create advanced power cells for their exosuits."
    },
    {
      "id": 52,
      "filename": "speaker_5_temp_1.1_topk_50_game_instructions_52.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and balanced vocabulary diversity using game_instructions style",
      "generation_time": "260.16s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 61,
      "filename": "speaker_5_temp_1.3_topk_20_short_61.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 20,
      "style": "short",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and focused and consistent word choices using short style",
      "generation_time": "164.93s",
      "text": "A pixelated spaceship drifts through an asteroid field."
    },
    {
      "id": 33,
      "filename": "speaker_2_temp_1.3_topk_50_accent_variation_33.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and balanced vocabulary diversity using accent_variation style",
      "generation_time": "149.59s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 39,
      "filename": "speaker_2_temp_1.3_topk_80_game_instructions_39.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 80,
      "style": "game_instructions",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and diverse and potentially creative phrasing using game_instructions style",
      "generation_time": "408.85s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    },
    {
      "id": 54,
      "filename": "speaker_5_temp_1.1_topk_80_short_54.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using short style",
      "generation_time": "279.87s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 78,
      "filename": "speaker_5_temp_1.3_topk_80_conversation_78.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and diverse and potentially creative phrasing using conversation style",
      "generation_time": "102.88s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 113,
      "filename": "speaker_7_temp_1.3_topk_50_accent_variation_113.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and balanced vocabulary diversity using accent_variation style",
      "generation_time": "317.30s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 83,
      "filename": "speaker_7_temp_1.1_topk_20_emotional_83.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and focused and consistent word choices using emotional style",
      "generation_time": "210.92s",
      "text": "[suspenseful] The countdown timer flashes red as oxygen levels drop to critical levels."
    },
    {
      "id": 87,
      "filename": "speaker_7_temp_1.1_topk_50_short_87.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using short style",
      "generation_time": "163.71s",
      "text": "A pixelated spaceship drifts through an asteroid field."
    },
    {
      "id": 32,
      "filename": "speaker_2_temp_1.3_topk_50_game_instructions_32.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and balanced vocabulary diversity using game_instructions style",
      "generation_time": "359.45s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 40,
      "filename": "speaker_2_temp_1.3_topk_80_accent_variation_40.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "150.21s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 106,
      "filename": "speaker_7_temp_1.3_topk_20_accent_variation_106.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and focused and consistent word choices using accent_variation style",
      "generation_time": "197.96s",
      "text": "[british] I say, this adventure is turning out to be quite splendid!"
    },
    {
      "id": 19,
      "filename": "speaker_2_temp_1.1_topk_80_game_instructions_19.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 80,
      "style": "game_instructions",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and diverse and potentially creative phrasing using game_instructions style",
      "generation_time": "174.12s",
      "text": "Press X to jump and hold Circle to charge your special attack."
    },
    {
      "id": 49,
      "filename": "speaker_5_temp_1.1_topk_50_technical_49.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 50,
      "style": "technical",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and balanced vocabulary diversity using technical style",
      "generation_time": "367.86s",
      "text": "Players can combine lithium deposits with thermal extractors to create advanced power cells for their exosuits."
    },
    {
      "id": 107,
      "filename": "speaker_7_temp_1.3_topk_50_short_107.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and balanced vocabulary diversity using short style",
      "generation_time": "185.31s",
      "text": "Epic orchestral music builds as stars appear in darkness."
    },
    {
      "id": 109,
      "filename": "speaker_7_temp_1.3_topk_50_technical_109.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 50,
      "style": "technical",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and balanced vocabulary diversity using technical style",
      "generation_time": "372.49s",
      "text": "The quantum entanglement device initializes its calibration sequence, emitting a soft blue glow throughout the laboratory."
    },
    {
      "id": 56,
      "filename": "speaker_5_temp_1.1_topk_80_technical_56.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using technical style",
      "generation_time": "287.04s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 122,
      "filename": "speaker_2_temp_0.9_topk_50_conversation_with_context_122.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 0.9,
      "topk": 50,
      "style": "conversation",
      "has_context": true,
      "description": "Fefemale voice with medium pitch with balanced expressivity and consistency and balanced vocabulary diversity using conversation style with conversation context",
      "generation_time": "228.05s",
      "text": "I'm not sure I understand. Could you explain that again?"
    },
    {
      "id": 119,
      "filename": "speaker_7_temp_1.3_topk_80_game_instructions_119.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 80,
      "style": "game_instructions",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and diverse and potentially creative phrasing using game_instructions style",
      "generation_time": "244.37s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 31,
      "filename": "speaker_2_temp_1.3_topk_50_conversation_31.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and balanced vocabulary diversity using conversation style",
      "generation_time": "126.17s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 117,
      "filename": "speaker_7_temp_1.3_topk_80_emotional_117.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 80,
      "style": "emotional",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and diverse and potentially creative phrasing using emotional style",
      "generation_time": "182.68s",
      "text": "[ominous] Something watches from the shadows, tracking your every move."
    },
    {
      "id": 5,
      "filename": "speaker_2_temp_1.1_topk_20_game_instructions_5.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using game_instructions style",
      "generation_time": "292.38s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    },
    {
      "id": 60,
      "filename": "speaker_5_temp_1.1_topk_80_accent_variation_60.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "175.36s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 46,
      "filename": "speaker_5_temp_1.1_topk_20_accent_variation_46.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and focused and consistent word choices using accent_variation style",
      "generation_time": "160.63s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 75,
      "filename": "speaker_5_temp_1.3_topk_80_medium_75.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and diverse and potentially creative phrasing using medium style",
      "generation_time": "393.35s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 45,
      "filename": "speaker_5_temp_1.1_topk_20_game_instructions_45.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and focused and consistent word choices using game_instructions style",
      "generation_time": "174.54s",
      "text": "Collect the blue crystals to upgrade your character's abilities in the skill tree."
    },
    {
      "id": 3,
      "filename": "speaker_2_temp_1.1_topk_20_emotional_3.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using emotional style",
      "generation_time": "196.39s",
      "text": "[suspenseful] The countdown timer flashes red as oxygen levels drop to critical levels."
    },
    {
      "id": 37,
      "filename": "speaker_2_temp_1.3_topk_80_emotional_37.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 80,
      "style": "emotional",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and diverse and potentially creative phrasing using emotional style",
      "generation_time": "233.98s",
      "text": "[melancholic] The melody echoes memories of a world long forgotten."
    },
    {
      "id": 12,
      "filename": "speaker_2_temp_1.1_topk_50_game_instructions_12.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and balanced vocabulary diversity using game_instructions style",
      "generation_time": "198.92s",
      "text": "Collect the blue crystals to upgrade your character's abilities in the skill tree."
    },
    {
      "id": 105,
      "filename": "speaker_7_temp_1.3_topk_20_game_instructions_105.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and focused and consistent word choices using game_instructions style",
      "generation_time": "227.72s",
      "text": "Collect the blue crystals to upgrade your character's abilities in the skill tree."
    },
    {
      "id": 98,
      "filename": "speaker_7_temp_1.1_topk_80_conversation_98.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and diverse and potentially creative phrasing using conversation style",
      "generation_time": "95.25s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 126,
      "filename": "speaker_7_temp_0.9_topk_50_conversation_with_context_126.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 0.9,
      "topk": 50,
      "style": "conversation",
      "has_context": true,
      "description": "Deep fefemale voice with mature tone with balanced expressivity and consistency and balanced vocabulary diversity using conversation style with conversation context",
      "generation_time": "763.22s",
      "text": "I'm not sure I understand. Could you explain that again?"
    },
    {
      "id": 82,
      "filename": "speaker_7_temp_1.1_topk_20_medium_82.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and focused and consistent word choices using medium style",
      "generation_time": "378.06s",
      "text": "Rhythmic tribal drums accompany the hero's journey through dense jungle foliage, occasionally interrupted by exotic wildlife calls."
    },
    {
      "id": 29,
      "filename": "speaker_2_temp_1.3_topk_50_technical_29.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 50,
      "style": "technical",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and balanced vocabulary diversity using technical style",
      "generation_time": "368.60s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 21,
      "filename": "speaker_2_temp_1.3_topk_20_short_21.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 20,
      "style": "short",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and focused and consistent word choices using short style",
      "generation_time": "161.40s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 4,
      "filename": "speaker_2_temp_1.1_topk_20_conversation_4.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using conversation style",
      "generation_time": "113.10s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 116,
      "filename": "speaker_7_temp_1.3_topk_80_technical_116.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and diverse and potentially creative phrasing using technical style",
      "generation_time": "407.13s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 24,
      "filename": "speaker_2_temp_1.3_topk_20_conversation_24.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and focused and consistent word choices using conversation style",
      "generation_time": "135.28s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 8,
      "filename": "speaker_2_temp_1.1_topk_50_medium_8.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and balanced vocabulary diversity using medium style",
      "generation_time": "456.08s",
      "text": "Electronic beeps and ambient synth create tension as the player navigates through a dimly lit abandoned research facility."
    },
    {
      "id": 163,
      "filename": "speaker_3_temp_1.3_topk_20_emotional_163.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 1.3,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Young female voice with higher pitch with maximum expressivity and creativity and focused and consistent word choices using emotional style",
      "generation_time": "216.87s",
      "text": "[excited] We've finally discovered the artifact after years of searching!"
    },
    {
      "id": 278,
      "filename": "speaker_6_temp_1.1_topk_80_conversation_278.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.1,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with high expressivity and natural variation and diverse and potentially creative phrasing using conversation style",
      "generation_time": "126.27s",
      "text": "I'm not sure I understand. Could you explain that again?"
    },
    {
      "id": 92,
      "filename": "speaker_1_temp_1.1_topk_50_game_instructions_92.wav",
      "exists": true,
      "speaker_id": 1,
      "temperature": 1.1,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Deep female voice with dramatic tone with high expressivity and natural variation and balanced vocabulary diversity using game_instructions style",
      "generation_time": "224.69s",
      "text": "Collect the blue crystals to upgrade your character's abilities in the skill tree."
    },
    {
      "id": 236,
      "filename": "speaker_4_temp_1.3_topk_80_technical_236.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.3,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with maximum expressivity and creativity and diverse and potentially creative phrasing using technical style",
      "generation_time": "355.87s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 207,
      "filename": "speaker_4_temp_1.1_topk_50_short_207.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.1,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with high expressivity and natural variation and balanced vocabulary diversity using short style",
      "generation_time": "139.85s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 150,
      "filename": "speaker_3_temp_1.1_topk_50_emotional_150.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 1.1,
      "topk": 50,
      "style": "emotional",
      "has_context": false,
      "description": "Young female voice with higher pitch with high expressivity and natural variation and balanced vocabulary diversity using emotional style",
      "generation_time": "195.87s",
      "text": "[ominous] Something watches from the shadows, tracking your every move."
    },
    {
      "id": 273,
      "filename": "speaker_6_temp_1.1_topk_50_accent_variation_273.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.1,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with high expressivity and natural variation and balanced vocabulary diversity using accent_variation style",
      "generation_time": "151.42s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 192,
      "filename": "speaker_4_temp_0.9_topk_50_game_instructions_192.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with balanced expressivity and consistency and balanced vocabulary diversity using game_instructions style",
      "generation_time": "204.35s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    },
    {
      "id": 200,
      "filename": "speaker_4_temp_0.9_topk_80_accent_variation_200.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with balanced expressivity and consistency and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "203.42s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 238,
      "filename": "speaker_4_temp_1.3_topk_80_conversation_238.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.3,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with maximum expressivity and creativity and diverse and potentially creative phrasing using conversation style",
      "generation_time": "127.46s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 201,
      "filename": "speaker_4_temp_1.1_topk_20_short_201.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.1,
      "topk": 20,
      "style": "short",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with high expressivity and natural variation and focused and consistent word choices using short style",
      "generation_time": "134.23s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 253,
      "filename": "speaker_6_temp_0.9_topk_50_accent_variation_253.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 0.9,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with balanced expressivity and consistency and balanced vocabulary diversity using accent_variation style",
      "generation_time": "281.16s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 190,
      "filename": "speaker_4_temp_0.9_topk_50_emotional_190.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 50,
      "style": "emotional",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with balanced expressivity and consistency and balanced vocabulary diversity using emotional style",
      "generation_time": "186.28s",
      "text": "[ominous] Something watches from the shadows, tracking your every move."
    },
    {
      "id": 156,
      "filename": "speaker_3_temp_1.1_topk_80_technical_156.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 1.1,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Young female voice with higher pitch with high expressivity and natural variation and diverse and potentially creative phrasing using technical style",
      "generation_time": "388.11s",
      "text": "The quantum entanglement device initializes its calibration sequence, emitting a soft blue glow throughout the laboratory."
    },
    {
      "id": 28,
      "filename": "speaker_0_temp_1.1_topk_50_medium_28.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 1.1,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Medium-pitched female voice with clear articulation with high expressivity and natural variation and balanced vocabulary diversity using medium style",
      "generation_time": "354.65s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 13,
      "filename": "speaker_2_temp_1.1_topk_50_accent_variation_13.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and balanced vocabulary diversity using accent_variation style",
      "generation_time": "242.07s",
      "text": "[british] I say, this adventure is turning out to be quite splendid!"
    },
    {
      "id": 48,
      "filename": "speaker_5_temp_1.1_topk_50_medium_48.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and balanced vocabulary diversity using medium style",
      "generation_time": "458.32s",
      "text": "The spacecraft engines roar to life, pushing against the planet's gravity as stars slowly become visible through the clearing atmosphere."
    },
    {
      "id": 94,
      "filename": "speaker_7_temp_1.1_topk_80_short_94.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and diverse and potentially creative phrasing using short style",
      "generation_time": "135.64s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 27,
      "filename": "speaker_2_temp_1.3_topk_50_short_27.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and balanced vocabulary diversity using short style",
      "generation_time": "445.42s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 47,
      "filename": "speaker_5_temp_1.1_topk_50_short_47.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and balanced vocabulary diversity using short style",
      "generation_time": "207.33s",
      "text": "A pixelated spaceship drifts through an asteroid field."
    },
    {
      "id": 115,
      "filename": "speaker_7_temp_1.3_topk_80_medium_115.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and diverse and potentially creative phrasing using medium style",
      "generation_time": "382.67s",
      "text": "Rhythmic tribal drums accompany the hero's journey through dense jungle foliage, occasionally interrupted by exotic wildlife calls."
    },
    {
      "id": 89,
      "filename": "speaker_7_temp_1.1_topk_50_technical_89.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "technical",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using technical style",
      "generation_time": "420.16s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 95,
      "filename": "speaker_7_temp_1.1_topk_80_medium_95.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and diverse and potentially creative phrasing using medium style",
      "generation_time": "407.95s",
      "text": "The spacecraft engines roar to life, pushing against the planet's gravity as stars slowly become visible through the clearing atmosphere."
    },
    {
      "id": 41,
      "filename": "speaker_5_temp_1.1_topk_20_short_41.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 20,
      "style": "short",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and focused and consistent word choices using short style",
      "generation_time": "125.38s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 64,
      "filename": "speaker_5_temp_1.3_topk_20_conversation_64.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and focused and consistent word choices using conversation style",
      "generation_time": "108.29s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 53,
      "filename": "speaker_5_temp_1.1_topk_50_accent_variation_53.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and balanced vocabulary diversity using accent_variation style",
      "generation_time": "175.56s",
      "text": "[british] I say, this adventure is turning out to be quite splendid!"
    },
    {
      "id": 20,
      "filename": "speaker_2_temp_1.1_topk_80_accent_variation_20.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "332.98s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 65,
      "filename": "speaker_5_temp_1.3_topk_20_game_instructions_65.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and focused and consistent word choices using game_instructions style",
      "generation_time": "229.57s",
      "text": "Press X to jump and hold Circle to charge your special attack."
    },
    {
      "id": 14,
      "filename": "speaker_2_temp_1.1_topk_80_short_14.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and diverse and potentially creative phrasing using short style",
      "generation_time": "300.86s",
      "text": "Epic orchestral music builds as stars appear in darkness."
    },
    {
      "id": 102,
      "filename": "speaker_7_temp_1.3_topk_20_medium_102.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "407.55s",
      "text": "Electronic beeps and ambient synth create tension as the player navigates through a dimly lit abandoned research facility."
    },
    {
      "id": 88,
      "filename": "speaker_7_temp_1.1_topk_50_medium_88.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using medium style",
      "generation_time": "410.19s",
      "text": "The spacecraft engines roar to life, pushing against the planet's gravity as stars slowly become visible through the clearing atmosphere."
    },
    {
      "id": 74,
      "filename": "speaker_5_temp_1.3_topk_80_short_74.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and diverse and potentially creative phrasing using short style",
      "generation_time": "214.41s",
      "text": "Epic orchestral music builds as stars appear in darkness."
    },
    {
      "id": 15,
      "filename": "speaker_2_temp_1.1_topk_80_medium_15.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and diverse and potentially creative phrasing using medium style",
      "generation_time": "369.79s",
      "text": "Rhythmic tribal drums accompany the hero's journey through dense jungle foliage, occasionally interrupted by exotic wildlife calls."
    },
    {
      "id": 36,
      "filename": "speaker_2_temp_1.3_topk_80_technical_36.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and diverse and potentially creative phrasing using technical style",
      "generation_time": "319.42s",
      "text": "Players can combine lithium deposits with thermal extractors to create advanced power cells for their exosuits."
    },
    {
      "id": 58,
      "filename": "speaker_5_temp_1.1_topk_80_conversation_58.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using conversation style",
      "generation_time": "105.83s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 124,
      "filename": "speaker_5_temp_0.9_topk_50_conversation_with_context_124.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.9,
      "topk": 50,
      "style": "conversation",
      "has_context": true,
      "description": "Smooth fefemale voice with warm tone with balanced expressivity and consistency and balanced vocabulary diversity using conversation style with conversation context",
      "generation_time": "434.29s",
      "text": "I'm not sure I understand. Could you explain that again?"
    },
    {
      "id": 17,
      "filename": "speaker_2_temp_1.1_topk_80_emotional_17.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 80,
      "style": "emotional",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with high expressivity and natural variation and diverse and potentially creative phrasing using emotional style",
      "generation_time": "215.00s",
      "text": "[suspenseful] The countdown timer flashes red as oxygen levels drop to critical levels."
    },
    {
      "id": 25,
      "filename": "speaker_2_temp_1.3_topk_20_game_instructions_25.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Fefemale voice with medium pitch with maximum expressivity and creativity and focused and consistent word choices using game_instructions style",
      "generation_time": "193.25s",
      "text": "Press X to jump and hold Circle to charge your special attack."
    },
    {
      "id": 73,
      "filename": "speaker_5_temp_1.3_topk_50_accent_variation_73.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and balanced vocabulary diversity using accent_variation style",
      "generation_time": "194.85s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 110,
      "filename": "speaker_7_temp_1.3_topk_50_emotional_110.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.3,
      "topk": 50,
      "style": "emotional",
      "has_context": false,
      "description": "Deep fefemale voice with mature tone with maximum expressivity and creativity and balanced vocabulary diversity using emotional style",
      "generation_time": "159.85s",
      "text": "[ominous] Something watches from the shadows, tracking your every move."
    },
    {
      "id": 63,
      "filename": "speaker_5_temp_1.3_topk_20_emotional_63.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Smooth fefemale voice with warm tone with maximum expressivity and creativity and focused and consistent word choices using emotional style",
      "generation_time": "182.98s",
      "text": "[melancholic] The melody echoes memories of a world long forgotten."
    },
    {
      "id": 267,
      "filename": "speaker_6_temp_1.1_topk_50_short_267.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.1,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with high expressivity and natural variation and balanced vocabulary diversity using short style",
      "generation_time": "201.29s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 215,
      "filename": "speaker_4_temp_1.1_topk_80_medium_215.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.1,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with high expressivity and natural variation and diverse and potentially creative phrasing using medium style",
      "generation_time": "429.17s",
      "text": "The spacecraft engines roar to life, pushing against the planet's gravity as stars slowly become visible through the clearing atmosphere."
    },
    {
      "id": 79,
      "filename": "speaker_1_temp_0.9_topk_80_game_instructions_79.wav",
      "exists": true,
      "speaker_id": 1,
      "temperature": 0.9,
      "topk": 80,
      "style": "game_instructions",
      "has_context": false,
      "description": "Deep female voice with dramatic tone with balanced expressivity and consistency and diverse and potentially creative phrasing using game_instructions style",
      "generation_time": "263.61s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    },
    {
      "id": 284,
      "filename": "speaker_6_temp_1.3_topk_20_conversation_284.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.3,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with maximum expressivity and creativity and focused and consistent word choices using conversation style",
      "generation_time": "121.32s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 139,
      "filename": "speaker_3_temp_0.9_topk_80_game_instructions_139.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 0.9,
      "topk": 80,
      "style": "game_instructions",
      "has_context": false,
      "description": "Young female voice with higher pitch with balanced expressivity and consistency and diverse and potentially creative phrasing using game_instructions style",
      "generation_time": "946.33s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 153,
      "filename": "speaker_3_temp_1.1_topk_50_accent_variation_153.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 1.1,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Young female voice with higher pitch with high expressivity and natural variation and balanced vocabulary diversity using accent_variation style",
      "generation_time": "213.86s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 247,
      "filename": "speaker_6_temp_0.9_topk_50_short_247.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 0.9,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with balanced expressivity and consistency and balanced vocabulary diversity using short style",
      "generation_time": "150.17s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 220,
      "filename": "speaker_4_temp_1.1_topk_80_accent_variation_220.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.1,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with high expressivity and natural variation and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "162.18s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 195,
      "filename": "speaker_4_temp_0.9_topk_80_medium_195.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with balanced expressivity and consistency and diverse and potentially creative phrasing using medium style",
      "generation_time": "439.37s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 182,
      "filename": "speaker_4_temp_0.9_topk_20_medium_182.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with balanced expressivity and consistency and focused and consistent word choices using medium style",
      "generation_time": "338.11s",
      "text": "Electronic beeps and ambient synth create tension as the player navigates through a dimly lit abandoned research facility."
    },
    {
      "id": 263,
      "filename": "speaker_6_temp_1.1_topk_20_emotional_263.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.1,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with high expressivity and natural variation and focused and consistent word choices using emotional style",
      "generation_time": "279.39s",
      "text": "[suspenseful] The countdown timer flashes red as oxygen levels drop to critical levels."
    },
    {
      "id": 147,
      "filename": "speaker_3_temp_1.1_topk_50_short_147.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 1.1,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Young female voice with higher pitch with high expressivity and natural variation and balanced vocabulary diversity using short style",
      "generation_time": "252.16s",
      "text": "Epic orchestral music builds as stars appear in darkness."
    },
    {
      "id": 179,
      "filename": "speaker_3_temp_1.3_topk_80_game_instructions_179.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 1.3,
      "topk": 80,
      "style": "game_instructions",
      "has_context": false,
      "description": "Young female voice with higher pitch with maximum expressivity and creativity and diverse and potentially creative phrasing using game_instructions style",
      "generation_time": "436.20s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 234,
      "filename": "speaker_4_temp_1.3_topk_80_short_234.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.3,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Authoritative female voice with gravitas with maximum expressivity and creativity and diverse and potentially creative phrasing using short style",
      "generation_time": "141.77s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 272,
      "filename": "speaker_6_temp_1.1_topk_50_game_instructions_272.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.1,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Energetic female voice with medium-high pitch with high expressivity and natural variation and balanced vocabulary diversity using game_instructions style",
      "generation_time": "329.76s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    }
  ]
};
