const voiceExplorationSamples = {
  "sample_text": "Various texts (see individual samples)",
  "base_path": "/home/tdeshane/movie_maker/hdmy5movie_voices/explore",
  "date_generated": "2025-03-13T23:58:36.843755",
  "samples": [
    {
      "id": 372,
      "filename": "speaker_4_temp_0.75_topk_50_medium_372.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.75,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Authoritative male voice with gravitas with moderate expressivity and natural flow and balanced vocabulary diversity using medium style",
      "generation_time": "208.74s",
      "text": "Electronic beeps and ambient synth create tension as the player navigates through a dimly lit abandoned research facility."
    },
    {
      "id": 34,
      "filename": "speaker_0_temp_0.9_topk_20_accent_variation_34.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.9,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Medium-pitched male voice with clear articulation with balanced expressivity and consistency and focused and consistent word choices using accent_variation style",
      "generation_time": "62.76s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 227,
      "filename": "speaker_2_temp_1.1_topk_20_emotional_227.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Female voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using emotional style",
      "generation_time": "118.56s",
      "text": "[excited] We've finally discovered the artifact after years of searching!"
    },
    {
      "id": 581,
      "filename": "speaker_6_temp_1.1_topk_20_game_instructions_581.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.1,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Energetic male voice with medium-high pitch with high expressivity and natural variation and focused and consistent word choices using game_instructions style",
      "generation_time": "150.48s",
      "text": "Press X to jump and hold Circle to charge your special attack."
    },
    {
      "id": 422,
      "filename": "speaker_4_temp_1.3_topk_20_medium_422.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Authoritative male voice with gravitas with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "282.51s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 276,
      "filename": "speaker_3_temp_0.5_topk_80_technical_276.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 0.5,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Young male voice with higher pitch with low randomness and consistent delivery and diverse and potentially creative phrasing using technical style",
      "generation_time": "197.55s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 18,
      "filename": "speaker_0_temp_0.75_topk_20_game_instructions_18.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.75,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Medium-pitched male voice with clear articulation with moderate expressivity and natural flow and focused and consistent word choices using game_instructions style",
      "generation_time": "586.32s",
      "text": "New quest available: 'The Lost Artifact' - Speak to the village elder to begin."
    },
    {
      "id": 151,
      "filename": "speaker_1_temp_1.1_topk_80_medium_151.wav",
      "exists": true,
      "speaker_id": 1,
      "temperature": 1.1,
      "topk": 80,
      "style": "medium",
      "has_context": false,
      "description": "Deep male voice with dramatic tone with high expressivity and natural variation and diverse and potentially creative phrasing using medium style",
      "generation_time": "228.07s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 338,
      "filename": "speaker_3_temp_1.3_topk_20_accent_variation_338.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 1.3,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Young male voice with higher pitch with maximum expressivity and creativity and focused and consistent word choices using accent_variation style",
      "generation_time": "98.63s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 677,
      "filename": "speaker_7_temp_1.1_topk_50_accent_variation_677.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "accent_variation",
      "has_context": false,
      "description": "Deep female voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using accent_variation style",
      "generation_time": "80.79s",
      "text": "[southern] Y'all better watch out for them critters in the swamp."
    },
    {
      "id": 394,
      "filename": "speaker_4_temp_0.9_topk_80_short_394.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Authoritative male voice with gravitas with balanced expressivity and consistency and diverse and potentially creative phrasing using short style",
      "generation_time": "85.23s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 255,
      "filename": "speaker_2_temp_1.3_topk_50_conversation_255.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Female voice with medium pitch with maximum expressivity and creativity and balanced vocabulary diversity using conversation style",
      "generation_time": "83.36s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 385,
      "filename": "speaker_4_temp_0.9_topk_20_game_instructions_385.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.9,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Authoritative male voice with gravitas with balanced expressivity and consistency and focused and consistent word choices using game_instructions style",
      "generation_time": "123.76s",
      "text": "Collect the blue crystals to upgrade your character's abilities in the skill tree."
    },
    {
      "id": 524,
      "filename": "speaker_5_temp_1.3_topk_80_technical_524.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 80,
      "style": "technical",
      "has_context": false,
      "description": "Smooth female voice with warm tone with maximum expressivity and creativity and diverse and potentially creative phrasing using technical style",
      "generation_time": "190.42s",
      "text": "The quantum entanglement device initializes its calibration sequence, emitting a soft blue glow throughout the laboratory."
    },
    {
      "id": 246,
      "filename": "speaker_2_temp_1.3_topk_20_medium_246.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Female voice with medium pitch with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "244.18s",
      "text": "Rhythmic tribal drums accompany the hero's journey through dense jungle foliage, occasionally interrupted by exotic wildlife calls."
    },
    {
      "id": 510,
      "filename": "speaker_5_temp_1.3_topk_20_medium_510.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Smooth female voice with warm tone with maximum expressivity and creativity and focused and consistent word choices using medium style",
      "generation_time": "191.25s",
      "text": "Electronic beeps and ambient synth create tension as the player navigates through a dimly lit abandoned research facility."
    },
    {
      "id": 298,
      "filename": "speaker_3_temp_0.9_topk_20_accent_variation_298.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 0.9,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Young male voice with higher pitch with balanced expressivity and consistency and focused and consistent word choices using accent_variation style",
      "generation_time": "144.84s",
      "text": "[british] I say, this adventure is turning out to be quite splendid!"
    },
    {
      "id": 448,
      "filename": "speaker_5_temp_0.5_topk_50_conversation_448.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.5,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth female voice with warm tone with low randomness and consistent delivery and balanced vocabulary diversity using conversation style",
      "generation_time": "68.90s",
      "text": "That's incredible news! When did you find out?"
    },
    {
      "id": 7,
      "filename": "speaker_0_temp_0.5_topk_50_technical_7.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.5,
      "topk": 50,
      "style": "technical",
      "has_context": false,
      "description": "Medium-pitched male voice with clear articulation with low randomness and consistent delivery and balanced vocabulary diversity using technical style",
      "generation_time": "184.53s",
      "text": "The procedurally generated ecosystem adapts to player actions, creating emergent gameplay scenarios unique to each playthrough."
    },
    {
      "id": 300,
      "filename": "speaker_3_temp_0.9_topk_50_medium_300.wav",
      "exists": true,
      "speaker_id": 3,
      "temperature": 0.9,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Young male voice with higher pitch with balanced expressivity and consistency and balanced vocabulary diversity using medium style",
      "generation_time": "254.68s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 167,
      "filename": "speaker_1_temp_1.3_topk_50_conversation_167.wav",
      "exists": true,
      "speaker_id": 1,
      "temperature": 1.3,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Deep male voice with dramatic tone with maximum expressivity and creativity and balanced vocabulary diversity using conversation style",
      "generation_time": "70.31s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 472,
      "filename": "speaker_5_temp_0.9_topk_20_conversation_472.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.9,
      "topk": 20,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth female voice with warm tone with balanced expressivity and consistency and focused and consistent word choices using conversation style",
      "generation_time": "67.53s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 68,
      "filename": "speaker_0_temp_1.1_topk_80_accent_variation_68.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 1.1,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Medium-pitched male voice with clear articulation with high expressivity and natural variation and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "180.74s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 51,
      "filename": "speaker_0_temp_1.1_topk_20_emotional_51.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 1.1,
      "topk": 20,
      "style": "emotional",
      "has_context": false,
      "description": "Medium-pitched male voice with clear articulation with high expressivity and natural variation and focused and consistent word choices using emotional style",
      "generation_time": "137.89s",
      "text": "[suspenseful] The countdown timer flashes red as oxygen levels drop to critical levels."
    },
    {
      "id": 458,
      "filename": "speaker_5_temp_0.75_topk_20_game_instructions_458.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.75,
      "topk": 20,
      "style": "game_instructions",
      "has_context": false,
      "description": "Smooth female voice with warm tone with moderate expressivity and natural flow and focused and consistent word choices using game_instructions style",
      "generation_time": "224.44s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    },
    {
      "id": 506,
      "filename": "speaker_5_temp_1.1_topk_80_conversation_506.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.1,
      "topk": 80,
      "style": "conversation",
      "has_context": false,
      "description": "Smooth female voice with warm tone with high expressivity and natural variation and diverse and potentially creative phrasing using conversation style",
      "generation_time": "61.37s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 230,
      "filename": "speaker_2_temp_1.1_topk_20_accent_variation_230.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 1.1,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Female voice with medium pitch with high expressivity and natural variation and focused and consistent word choices using accent_variation style",
      "generation_time": "88.53s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 613,
      "filename": "speaker_6_temp_1.3_topk_80_emotional_613.wav",
      "exists": true,
      "speaker_id": 6,
      "temperature": 1.3,
      "topk": 80,
      "style": "emotional",
      "has_context": false,
      "description": "Energetic male voice with medium-high pitch with maximum expressivity and creativity and diverse and potentially creative phrasing using emotional style",
      "generation_time": "112.64s",
      "text": "[melancholic] The melody echoes memories of a world long forgotten."
    },
    {
      "id": 675,
      "filename": "speaker_7_temp_1.1_topk_50_conversation_675.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "conversation",
      "has_context": false,
      "description": "Deep female voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using conversation style",
      "generation_time": "81.61s",
      "text": "Hey there! Have you tried the new game yet?"
    },
    {
      "id": 23,
      "filename": "speaker_0_temp_0.75_topk_50_game_instructions_23.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.75,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Medium-pitched male voice with clear articulation with moderate expressivity and natural flow and balanced vocabulary diversity using game_instructions style",
      "generation_time": "208.00s",
      "text": "Mission objective: Infiltrate the enemy base and retrieve the stolen data."
    },
    {
      "id": 170,
      "filename": "speaker_1_temp_1.3_topk_80_short_170.wav",
      "exists": true,
      "speaker_id": 1,
      "temperature": 1.3,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Deep male voice with dramatic tone with maximum expressivity and creativity and diverse and potentially creative phrasing using short style",
      "generation_time": "92.38s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 676,
      "filename": "speaker_7_temp_1.1_topk_50_game_instructions_676.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 1.1,
      "topk": 50,
      "style": "game_instructions",
      "has_context": false,
      "description": "Deep female voice with mature tone with high expressivity and natural variation and balanced vocabulary diversity using game_instructions style",
      "generation_time": "115.45s",
      "text": "Press X to jump and hold Circle to charge your special attack."
    },
    {
      "id": 645,
      "filename": "speaker_7_temp_0.9_topk_20_short_645.wav",
      "exists": true,
      "speaker_id": 7,
      "temperature": 0.9,
      "topk": 20,
      "style": "short",
      "has_context": false,
      "description": "Deep female voice with mature tone with balanced expressivity and consistency and focused and consistent word choices using short style",
      "generation_time": "95.34s",
      "text": "Dawn breaks over a cyberpunk cityscape."
    },
    {
      "id": 224,
      "filename": "speaker_2_temp_0.9_topk_80_accent_variation_224.wav",
      "exists": true,
      "speaker_id": 2,
      "temperature": 0.9,
      "topk": 80,
      "style": "accent_variation",
      "has_context": false,
      "description": "Female voice with medium pitch with balanced expressivity and consistency and diverse and potentially creative phrasing using accent_variation style",
      "generation_time": "107.80s",
      "text": "[whisper] We need to be very quiet. The guards are right around the corner."
    },
    {
      "id": 10,
      "filename": "speaker_0_temp_0.5_topk_80_short_10.wav",
      "exists": true,
      "speaker_id": 0,
      "temperature": 0.5,
      "topk": 80,
      "style": "short",
      "has_context": false,
      "description": "Medium-pitched male voice with clear articulation with low randomness and consistent delivery and diverse and potentially creative phrasing using short style",
      "generation_time": "99.67s",
      "text": "Ancient ruins glow with mysterious blue energy."
    },
    {
      "id": 516,
      "filename": "speaker_5_temp_1.3_topk_50_medium_516.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 1.3,
      "topk": 50,
      "style": "medium",
      "has_context": false,
      "description": "Smooth female voice with warm tone with maximum expressivity and creativity and balanced vocabulary diversity using medium style",
      "generation_time": "317.86s",
      "text": "The camera pans slowly across a desolate landscape, revealing the remnants of an ancient civilization buried beneath crimson sand."
    },
    {
      "id": 371,
      "filename": "speaker_4_temp_0.75_topk_50_short_371.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 0.75,
      "topk": 50,
      "style": "short",
      "has_context": false,
      "description": "Authoritative male voice with gravitas with moderate expressivity and natural flow and balanced vocabulary diversity using short style",
      "generation_time": "87.05s",
      "text": "Lava bubbles around an obsidian fortress."
    },
    {
      "id": 406,
      "filename": "speaker_4_temp_1.1_topk_20_accent_variation_406.wav",
      "exists": true,
      "speaker_id": 4,
      "temperature": 1.1,
      "topk": 20,
      "style": "accent_variation",
      "has_context": false,
      "description": "Authoritative male voice with gravitas with high expressivity and natural variation and focused and consistent word choices using accent_variation style",
      "generation_time": "119.95s",
      "text": "[robotic] Initiating primary protocol. Scanning environment for threats."
    },
    {
      "id": 456,
      "filename": "speaker_5_temp_0.75_topk_20_medium_456.wav",
      "exists": true,
      "speaker_id": 5,
      "temperature": 0.75,
      "topk": 20,
      "style": "medium",
      "has_context": false,
      "description": "Smooth female voice with warm tone with moderate expressivity and natural flow and focused and consistent word choices using medium style",
      "generation_time": "259.63s",
      "text": "The spacecraft engines roar to life, pushing against the planet's gravity as stars slowly become visible through the clearing atmosphere."
    }
  ]
};